<?php

/**
 * Implements hook_services_resources().
 */
function thegreatnykz_services_resources() {
  $resources = array();

  $resources['nykzuser'] = array('operations' => array(),'actions' => array(),);
  $resources['nykzboard'] = array('operations' => array(),'actions' => array(),);
  $resources['nykzpost'] = array('operations' => array(),'actions' => array(),);

  $resources['nykzuser']['actions']['login'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzuser',
      ),
    'callback' => '_handler_login',
    'args' => array(
      array(
        'name' => 'userid',
        'optional' => FALSE,
        'source' => array('data' => 'userid'),
        'type' => 'string',
        ),
      array(
        'name' => 'password',
        'optional' => FALSE,
        'source' => array('data' => 'password'),
        'type' => 'string',
        ),
      ),
    'access arguments' => array('nykzlogin'),
    );

  $resources['nykzuser']['actions']['whoami'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzuser',
      ),
    'callback' => '_handler_whoami',
    'access arguments' => array('nykzlogin'),
    );

  $resources['nykzuser']['operations']['index'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzuser',
      ),
    'callback' => '_handler_nykzuser_index',
    'access arguments' => array('nykzbasic'),
    );
  $resources['nykzuser']['operations']['retrieve'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzuser',
      ),
    'callback' => '_handler_nykzuser_retrieve',
    'args' => array(
      array(
        'name' => 'userid',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'string',
        ),
    ),
    'access arguments' => array('nykzbasic'),
    );

  $resources['nykzboard']['operations']['index'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzboard',
      ),
    'callback' => '_handler_nykzboard_index',
    'access arguments' => array('nykzbasic'),
    );

  $resources['nykzboard']['actions']['show'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzboard',
      ),
    'callback' => '_handler_nykzboard_show',
    'args' => array(
      array(
        'name' => 'boardName',
        'optional' => FALSE,
        'source' => array('data' => 'boardName'),
        'type' => 'string',
        ),
      array(
        'name' => 'start',
        'optional' => TRUE,
        'source' => array('data' => 'start'),
        'type' => 'int',
        'default value' => 100000,
        ),
      array(
        'name' => 'count',
        'optional' => TRUE,
        'source' => array('data' => 'count'),
        'type' => 'int',
        'default value' => 20,
        ),
      ),
    'access callback' => '_access_nykzboard',
    'access callback file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzboard',
      ),
    'access arguments append' => TRUE,
    );

  $resources['nykzpost']['actions']['show'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzpost',
      ),
    'callback' => '_handler_nykzpost_show',
    'args' => array(
      array(
        'name' => 'boardName',
        'optional' => FALSE,
        'source' => array('data' => 'boardName'),
        'type' => 'string',
        ),
      array(
        'name' => 'filename',
        'optional' => FALSE,
        'source' => array('data' => 'filename'),
        'type' => 'string',
        ),
      ),
    'access callback' => '_access_nykzboard',
    'access callback file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzboard',
      ),
    'access arguments append' => TRUE,
    );
  $resources['nykzpost']['actions']['create'] = array(
    'file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzpost',
      ),
    'callback' => '_handler_nykzpost_create',
    'args' => array(
      array(
        'name' => 'boardName',
        'optional' => FALSE,
        'source' => array('data' => 'boardName'),
        'type' => 'string',
        ),
      array(
        'name' => 'title',
        'optional' => FALSE,
        'source' => array('data' => 'title'),
        'type' => 'string',
        ),
      array(
        'name' => 'content',
        'optional' => FALSE,
        'source' => array('data' => 'content'),
        'type' => 'string',
        ),
      array(
        'name' => 'reid',
        'optional' => TRUE,
        'source' => array('data' => 'reid'),
        'type' => 'string',
        ),
      ),
    'access callback' => '_access_nykzboard',
    'access callback file' => array(
      'type' => 'inc',
      'module' => 'thegreatnykz',
      'name' => 'resources/nykzboard',
      ),
    'access arguments append' => TRUE,
    );

  return $resources;
}

// implements hook_permission
function thegreatnykz_permission() {
  return array(
    'nykzbasic' => array(
      'title' => t('普通用户权限'),
      'description' => t('普通用户权限'),
    ),
    'nykzlogin' => array(
      'title' => t('南阳客栈用户登陆权限'),
      'description' => t('给匿名用户这个权限就好了。。。'),
    ),
  );
}

// implements hook_enable
function thegreatnykz_enable(){
  if (!field_info_field('field_udid')) {
    # 存储用户的udid
    $field = array('field_name' => 'field_udid', 'type' => 'text','cardinality' => FIELD_CARDINALITY_UNLIMITED);
    $field = field_create_field($field);
    # Create the instance on the bundle.
    $instance = array(
      'field_name' => $field['field_name'],
      'entity_type' => 'user',
      'bundle' => 'user',
      'label' => 'udid',
      'description' => '',
      'required' => FALSE,
      'settings' => array(
        'user_register_form' => 1,
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    );
    field_create_instance($instance);
    drupal_set_message($field['field_name'].' was created.');
  }
  if (!field_info_field('field_uploads')) {
    # 存储用户上传的文件名
    $field = array('field_name' => 'field_uploads', 'type' => 'text','cardinality' => FIELD_CARDINALITY_UNLIMITED);
    $field = field_create_field($field);
    $instance = array(
      'field_name' => $field['field_name'],
      'entity_type' => 'user',
      'bundle' => 'user',
      'label' => 'udid',
      'description' => '',
      'required' => FALSE,
      'settings' => array(
        'user_register_form' => 1,
      ),
      'widget' => array(
        'type' => 'textfield',
      ),
    );
    field_create_instance($instance);
    drupal_set_message($field['field_name'].' was created.');
  }

  if(!in_array("nykzuser", user_roles())){
    // 权限：普通用户
    $role = new stdClass();
    $role->name = 'nykzuser';
    $role->weight = 3;
    user_role_save($role);
    user_role_grant_permissions($role->rid,array(
      'read privatemsg',
      'write privatemsg',
      'delete privatemsg',
      'reply only privatemsg',
      'select text format for privatemsg',
      'nykzbasic',
      ));
  }
  if(!in_array("boardmaster", user_roles())){
    // 权限：板主
    $role = new stdClass();
    $role->name = 'boardmaster';
    $role->weight = 4;
    user_role_save($role);
  }
  if(!in_array("god", user_roles())){
    // 权限：站长
    $role = new stdClass();
    $role->name = 'god';
    $role->weight = 5;
    user_role_save($role);
  }
}
