#
# CVS: $Id: Makefile,v 1.2 2004/06/29 14:59:22 rwzmm Exp $
#
#################################################################

all: deljunk

deljunk:
	$(CC) -o deljunk deljunk.c -I../../include

clean: /tmp
	-rm -fr *~ *.o *.BAK

# DO NOT DELETE
