#!/usr/bin/env python
# encoding: utf-8


def build(bld):
        t = bld.new_task_gen(
                features     = 'cc cshlib',
                source  = bld.path.ant_glob('*.c'),
                target       = 'ntwww',
                includes     = '. .. ../modules ../tpl',
                uselib = 'GLIB',
                usetpl = 'tpl',
                install_path = '${BBSHOME}/httpd/pages'
        )
